apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: annotrelease
  namespace: gloo-crd
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/vs.yaml
      sourceRef:
        kind: GitRepository
        name: chartsrepo
        namespace: flux-system
      interval: 1m
  values:
    annotCount: 3